docker-deploy/web-app/miniUPS/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')) # 加入app对应urls
]

docker-deploy/web-app/website/urls.py
# demo/urls.py

from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "website"
urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('track/<int:id>', views.track, name='track'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('account/', views.account, name='account'),
    path('orders/', views.orders, name='orders'),
    path('change_dest/<int:package_id>/<int:truck_id>',
         views.change_dest, name='change_dest'),
    path('resend/<int:package_id>', views.resend, name='resend'),
    # path('account/package/', views.package_detail, name='package_detail'),
]

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

docker-deploy/web-app/templates/account.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Profile Page</title>
</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <!-- Container wrapper -->
          <div class="container">
      
              <!-- Toggle button -->
              <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                  data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false"
                  aria-label="Toggle navigation">
                  <i class="fas fa-bars"></i>
              </button>
      
              <!-- Collapsible wrapper -->
              <div class="collapse navbar-collapse" id="navbarButtonsExample">
                  <!-- Left links -->
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:index' %}">UPS Service</a>
                    </li>
                    {% if is_login%}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:orders' %}">Orders</a>
                    </li>
                    {%endif%}
                  </ul>
                  <!-- Left links -->
      
                  <div class="d-flex align-items-center">
                      <div class="dropdown">
                          <button class="btn btn-outline-danger dropdown-toggle" type="button" id="dropdownMenuButton1"
                              data-bs-toggle="dropdown" aria-expanded="false" data-mdb-ripple-color="dark">
                              profile
                          </button>
                          
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                              <li><a class="dropdown-item" href="{% url 'website:account' %}">My Profile</a></li>
                              {% comment %} <li><a class="dropdown-item" href="{% url 'website:edit_profile' %}">Edit Profile</a></li> {% endcomment %}
                              <li><a class="dropdown-item" href="{% url 'website:logout' %}">Log out</a></li>
                          </ul>
                      </div>
                  </div>
              </div>
              <!-- Collapsible wrapper -->
          </div>
          <!-- Container wrapper -->
      </nav>
      </header>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <div class="container bootdey flex-grow-1 container-p-y">

        <div class="media align-items-center py-3 mb-3">
            <!-- <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" -->
            <!-- class="d-block ui-w-100 rounded-circle"> -->
            <div class="media-body ml-4">
                <h4 class="font-weight-bold mb-0">
                    {% comment %} <span class="text-muted font-weight-normal">@{{ user.username }}</span> {% endcomment %}
                </h4>
                {% comment %} <div class="text-muted mb-2">ID: {{user.email}}</div> {% endcomment %}
            </div>
        </div>

        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-md-9 col-lg-7 col-xl-5">
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-4">
                  <div class="d-flex text-black">
                    <div class="flex-shrink-0">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
                    </div>
                    <div class="flex-grow-1 ms-3">
                      <h5 class="mb-1">{{user.username}}</h5>
                      <p class="mb-2 pb-1" style="color: #2b2a2a;">email: {{user.email}}</p>
                      <div class="d-flex justify-content-start rounded-3 p-2 mb-2" style="background-color: #efefef;">
                        <div>
                          <p class="small text-muted mb-1">Owned packages</p>
                          <p class="mb-0">{{packages_num}}</p>
                        </div>
                        <div class="px-3">
                          <p class="small text-muted mb-1">Delivered Packages</p>
                          <p class="mb-0">{{delivered_pac}}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
</body>

</html>

docker-deploy/web-app/templates/change_dest.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Order Page</title>
    <style>
        .scroll-section {
            max-height: 100px;
            overflow-y: auto;
          }
    </style>

</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <!-- Container wrapper -->
          <div class="container">
      
              <!-- Toggle button -->
              <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                  data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false"
                  aria-label="Toggle navigation">
                  <i class="fas fa-bars"></i>
              </button>
      
              <!-- Collapsible wrapper -->
              <div class="collapse navbar-collapse" id="navbarButtonsExample">
                  <!-- Left links -->
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:index' %}">UPS Service</a>
                    </li>
                    {% if is_login%}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:orders' %}">Orders</a>
                    </li>
                    {%endif%}
                  </ul>
                  <!-- Left links -->
      
                  <div class="d-flex align-items-center">
                    <div class="dropdown">
                        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            profile
                        </button>
                        
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="{% url 'website:account' %}">My Profile</a></li>
                            {% comment %} <li><a class="dropdown-item" href="{% url 'website:edit_profile' %}">Edit Profile</a></li> {% endcomment %}
                            <li><a class="dropdown-item" href="{% url 'website:logout' %}">Log out</a></li>
                        </ul>
                    </div>
                </div>
              </div>
              <!-- Collapsible wrapper -->
          </div>
          <!-- Container wrapper -->
      </nav>
    </header>
    <div class="container py-5 h-100">
        {% if error_message %}
            <div class="alert alert-primary" data-dismiss="alert">
                {{error_message}}
            </div>
            {% endif %}
    {% comment %} action="{% url 'website:change_dest' %}" {% endcomment %}
        <form method="post">
            {% csrf_token %}
            {% if error_message %}
            <div class="alert alert-primary" data-dismiss="alert">
                {{error_message}}
            </div>
            {% endif %}
            <!-- x -->
            <div class="form-outline mb-4">
            {{dest_form.x}}
            </div>
            <!-- y -->
            <div class="form-outline mb-4">
            {{dest_form.y}}
            </div>
            <!-- Submit button -->
            <div class="d-flex justify-content-around align-items-center mb-4">
                <button type="submit" class="btn btn-danger btn-lg btn-block">submit</button>
            </div>
           
        </form>
    </div>
</body>
</html>

docker-deploy/web-app/templates/index.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    {% comment %} <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css" media="all"> {% endcomment %}

    <style>
      html,
      body,
      .intro {
          height: 100%;
      }
      .bg-image-vertical {
          position: relative;
          overflow: hidden;
          background-repeat: no-repeat;
          background-position: right center;
          background-size: auto 100%;
      }
      .form-outline .form-control:focus~.form-notch .form-notch-leading {
          border-top: 0.125rem solid #EFD3E4;
          border-bottom: 0.125rem solid #EFD3E4;
          border-left: 0.125rem solid #EFD3E4;
      }
      .form-outline .form-control:focus~.form-notch .form-notch-middle {
          border-color: #EFD3E4;
      }
      .form-outline .form-control:focus~.form-notch .form-notch-trailing {
          border-top: 0.125rem solid #EFD3E4;
          border-bottom: 0.125rem solid #EFD3E4;
          border-right: 0.125rem solid #EFD3E4;
      }
      .form-outline .form-control:focus~.form-label {
          color: #EFD3E4;
      }
      .autocomplete-input.focused~.form-notch .form-notch-leading {
          border-top: 2px solid #EFD3E4;
          border-bottom: 2px solid #EFD3E4;
          border-left: 2px solid #EFD3E4;
          transition: all 0.2s linear;
      }
      .autocomplete-input.focused~.form-notch .form-notch-middle {
          border-color: #EFD3E4;
      }
      .autocomplete-input.focused~.form-notch .form-notch-trailing {
          border-color: #EFD3E4;
      }
      .autocomplete-input.focused~.autocomplete-label {
          color: #EFD3E4;
      }
    </style>
</head>
<body>

<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Container wrapper -->
    <div class="container">

        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
            data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:index' %}">UPS Service</a>
              </li>
              {% if is_login%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:orders' %}">Orders</a>
              </li>
              {%endif%}
            </ul>
            <!-- Left links -->

            <div class="d-flex align-items-center">
                <div class="dropdown">
                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        profile
                    </button>
                    
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        {% if is_login%}
                          <li><a class="dropdown-item" href="{% url 'website:account' %}">My Profile</a></li>
                          {% comment %} <li><a class="dropdown-item" href="{% url 'website:edit_profile' %}">Edit Profile</a></li> {% endcomment %}
                          <li><a class="dropdown-item" href="{% url 'website:logout' %}">Log out</a></li>
                        {% else %}
                          <li><a class="dropdown-item" href="{% url 'website:login' %}">Login</a></li>
                        {%endif%}
                    </ul>
                </div>
            </div>
        </div>
        <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
</nav>
</header>

    <section class="intro">
        <div class="bg-image-vertical h-100" style="background-color: #EFD3E4;
                background-image: url(https://mdbootstrap.com/img/Photos/new-templates/search-box/img1.jpg);
              ">
          <div class="mask d-flex align-items-center h-100">
            <div class="container">
              <p class="display-4 font-weight-bold mb-5 text-dark">Track your package here</p>
              <div class="card">
                <div class="card-body">
                  <div class="row justify-content-center">
                    {% if error_message %}
                        <div class="alert alert-primary" data-dismiss="alert">
                            {{error_message}}
                        </div>
                      {% endif %}
                    <form class="mx-1 mx-md-4 input-group" action="{% url 'website:index' %}" method="post">
                      {% csrf_token %}
                      <div class="col-md-6 mb-3 mb-md-0">
                        <div id="basic" class="form-outline">
                          {{track_form.trackingid}}
                          <label class="form-label" for="form1">What are you looking for?</label>
                        </div>
                      </div>
                      <div class="col-md-2">
                        <button class="btn btn-outline-danger" type="submit" data-mdb-ripple-color="dark">
                          Search
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</body>
</html>

docker-deploy/web-app/templates/orders.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Change dest addr</title>
    <style>
        .scroll-section {
            max-height: 100px;
            overflow-y: auto;
          }
    </style>

</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <!-- Container wrapper -->
          <div class="container">
      
              <!-- Toggle button -->
              <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                  data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false"
                  aria-label="Toggle navigation">
                  <i class="fas fa-bars"></i>
              </button>
      
              <!-- Collapsible wrapper -->
              <div class="collapse navbar-collapse" id="navbarButtonsExample">
                  <!-- Left links -->
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:index' %}">UPS Service</a>
                    </li>
                    {% if is_login%}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:orders' %}">Orders</a>
                    </li>
                    {%endif%}
                  </ul>
                  <!-- Left links -->
      
                  <div class="d-flex align-items-center">
                    <div class="dropdown">
                        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            profile
                        </button>
                        
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="{% url 'website:account' %}">My Profile</a></li>
                            {% comment %} <li><a class="dropdown-item" href="{% url 'website:edit_profile' %}">Edit Profile</a></li> {% endcomment %}
                            <li><a class="dropdown-item" href="{% url 'website:logout' %}">Log out</a></li>
                        </ul>
                    </div>
                </div>
              </div>
              <!-- Collapsible wrapper -->
          </div>
          <!-- Container wrapper -->
      </nav>
    </header>
    <div class="container py-5 h-100">
        <div class="d-flex align-items-center">
            <img
                src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                alt=""
                style="width: 45px; height: 45px"
                class="rounded-circle"
                />
            <div class="ms-3">
              <p class="fw-bold mb-1">{{user.username}}</p>
              <p class="text-muted mb-0">{{user.email}}</p>
            </div>
          </div>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
          <tr>
            <th>Package id</th>
            <th>Truck</th>
            <th>Status</th>
            <th>Dest addt</th>
            <th>Change dest</th>
            <th>Items</th>
          </tr>
        </thead>
        <tbody>
            {% for package in user_packages %}
            <tr>
              <td>
                  <p class="fw-normal mb-1">{{package.tracking_id}}</p>
              </td>
              <td>
                <p class="fw-normal mb-1">{{package.truckid.truckid}}</p>
              </td>
              <td>
                  <p class="fw-normal mb-1">{{package.status}}</p>
                </td>
              <td>
                  <p class="fw-normal mb-1">{{package.x}}, {{package.y}}</p>
              </td>
              <td>
              {% if package.status == 'in WH' or package.status == 'loading'%}
                  <button class="btn btn-outline-danger" type="submit" onclick="location.href='{% url 'website:change_dest' package_id=package.shipment_id truck_id=package.truckid.truckid%}'">
                    Change
                  </button> 
              {%elif package.status == 'delivered' %}
                  <button class="btn btn-outline-danger" type="submit" onclick="location.href='{% url 'website:resend' package_id=package.shipment_id %}'">
                    Resend
                  </button> 
              {%else%}
              <button class="btn btn-outline-danger" disabled>
                Change
              </button>
              {%endif%}
            </td>
              <td>
                <table class="table table-striped table-sm">
                  <thead>
                    <tr class="info">
                      <th>Description</th>
                      <th>Count</th>
                    </tr>
                  </thead>
                  <tbody>	
                    {% for item in pac_items%}
                    {% if item.tracking_id.tracking_id == package.tracking_id %}
                      <tr>
                        <td>
                          <p class="fw-normal mb-1">{{item.description}}</p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1">{{item.count}}</p>
                        </td>
                      </tr>
                    {%endif%}
                    {%endfor%}
                  </tbody>
                </table>
              </td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
</body>
</html>

docker-deploy/web-app/templates/track.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Track Page</title>
    <style>
        .timeline-steps {
            margin-top: 100px;
            display: flex;
            justify-content: center;
            flex-wrap: wrap
        }

        .timeline-steps .timeline-step {
            align-items: center;
            display: flex;
            flex-direction: column;
            position: relative;
            margin: 1rem
        }

        @media (min-width:768px) {
            .timeline-steps .timeline-step:not(:last-child):after {
                content: "";
                display: block;
                border-top: .25rem dotted #ff4d4d;
                width: 3.46rem;
                position: absolute;
                left: 7.5rem;
                top: .3125rem
            }
            .timeline-steps .timeline-step:not(:first-child):before {
                content: "";
                display: block;
                border-top: .25rem dotted #ff4d4d;
                width: 3.8125rem;
                position: absolute;
                right: 7.5rem;
                top: .3125rem
            }
        }

        .timeline-steps .timeline-content {
            width: 10rem;
            text-align: center
        }

        .timeline-steps .timeline-content .inner-circle {
            border-radius: 1.5rem;
            height: 1rem;
            width: 1rem;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            background-color: #ff4d4d
        }

        .timeline-steps .timeline-content .inner-circle:before {
            content: "";
            background-color: #ff4d4d;
            display: inline-block;
            height: 3rem;
            width: 3rem;
            min-width: 3rem;
            border-radius: 6.25rem;
            opacity: .5
        }
        </style>
</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <!-- Container wrapper -->
          <div class="container">
      
              <!-- Toggle button -->
              <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                  data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false"
                  aria-label="Toggle navigation">
                  <i class="fas fa-bars"></i>
              </button>
      
              <!-- Collapsible wrapper -->
              <div class="collapse navbar-collapse" id="navbarButtonsExample">
                  <!-- Left links -->
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:index' %}">UPS Service</a>
                    </li>
                    {% if is_login%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:orders' %}">Orders</a>
                    </li>
                    {%endif%}
                  </ul>
                  <!-- Left links -->
      
                  <div class="d-flex align-items-center">
                      <div class="dropdown">
                          <button class="btn btn-outline-danger dropdown-toggle" type="button" id="dropdownMenuButton1"
                              data-bs-toggle="dropdown" aria-expanded="false" data-mdb-ripple-color="dark">
                              profile
                          </button>
                          
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            {% if is_login%}
                            <li><a class="dropdown-item" href="{% url 'website:account' %}">My Profile</a></li>
                            {% comment %} <li><a class="dropdown-item" href="{% url 'website:edit_profile' %}">Edit Profile</a></li> {% endcomment %}
                            <li><a class="dropdown-item" href="{% url 'website:logout' %}">Log out</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'website:login' %}">Login</a></li>
                            {%endif%}
                          </ul>
                      </div>
                  </div>
              </div>
              <!-- Collapsible wrapper -->
          </div>
          <!-- Container wrapper -->
      </nav>
    </header>
    <div class="container">                      
        <div class="row text-center justify-content-center mb-5">
            <div class="col-xl-6 col-lg-8">
                <h2 class="font-weight-bold", style="margin-top: 50px">Package {{package.tracking_id}}</h2>
             </div>
        </div>
        <div class="row text-center justify-content-center mb-5">
            {% if message %}
                <div class="alert alert-primary" data-dismiss="alert">
                    {{message}}
                </div>
            {% endif %}
            {% if package.user == None and is_login == True%}
                <form class="mx-1 mx-md-4 input-group" action="{% url 'website:track' id=package.tracking_id %}" method="post">
                    {% csrf_token %}
                    <div class="d-grid gap-3 col-4 mx-auto">
                        <button class="btn btn-outline-danger" type="submit" >Bind this package</button>
                    </div>
                </form>
            {% else %}
                <div class="d-grid gap-3 col-4 mx-auto">
                    <button class="btn btn-outline-danger" type="button" disabled>Bind this package</button>
                </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <div class="timeline-steps aos-init aos-animate" data-aos="fade-up">
                    <div class="timeline-step">
                        <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2003">
                            <div class="inner-circle"></div>
                            <p class="h6 mt-3 mb-1">In the Warehouse</p>
                            <p class="h6 text-muted mb-0 mb-lg-0">dest addr: ({{package.x}}, {{package.y}}) </p>
                        </div>
                    </div>
                    {% comment %} package status: in WH, loading, loaded, delivering, delivered {% endcomment %}
                    {%if package.status != "in WH" %}
                        <div class="timeline-step">
                            <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2004">
                                <div class="inner-circle"></div>
                                <p class="h6 mt-3 mb-1">Loading</p>
                                <p class="h6 text-muted mb-0 mb-lg-0">Truck: {{package.truckid.truckid}}</p>
                            </div>
                        </div>
                        {% if package.status != "loading" %}
                            <div class="timeline-step">
                                <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2005">
                                    <div class="inner-circle"></div>
                                    <p class="h6 mt-3 mb-1">Loaded</p>
                                    <p class="h6 text-muted mb-0 mb-lg-0">Truck: {{package.truckid.truckid}}</p>
                                </div>
                            </div>
                            {% if package.status != "loaded" %}
                                <div class="timeline-step">
                                    <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2010">
                                        <div class="inner-circle"></div>
                                        <p class="h6 mt-3 mb-1">Delivering</p>
                                        <p class="h6 text-muted mb-0 mb-lg-0">dest addr: ({{package.x}}, {{package.y}}) </p>
                                    </div>
                                </div>
                                {% if package.status != "delivering" %}
                                    <div class="timeline-step mb-0">
                                        <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2020">
                                            <div class="inner-circle"></div>
                                            <p class="h6 mt-3 mb-1">Delivered</p>
                                            <p class="h6 text-muted mb-0 mb-lg-0">dest addr: ({{package.x}}, {{package.y}}) </p>
                                        </div>
                                    </div>
                                {%endif%}
                            {%endif%}
                        {%endif%}
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
  <!-- Section: Timeline -->
</body>
</html>